wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1635351883
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 16
      4: 3.8.8
      5: 0.12.5
      8:
      - 1
      - 5
alpha:
  desc: null
  value: 1
eps:
  desc: null
  value: 36
gamma:
  desc: null
  value: 0.1
kernel:
  desc: null
  value: laplacian
